### ISSUE TITLE
Identify the fix the problem where mob can't be spawn by spawn egg a few short time after player joined

### ISSUE THREAD

**Issue by maxxie114** [2B2TMCBE/MobPlugin#2]
the mob can't be spawn by spawn egg sometimes after the player joined the server for about a minute

**Comment by maxxie114** [comment]
Might have to do with inventory open, same problem as the water placement

**Comment by andrew121410** [comment]
Is this issue fixed?

**Comment by maxxie114** [comment]
> Is this issue fixed?

yes its fixed
