### ISSUE TITLE
Add new Spawn task

### ISSUE THREAD

**Issue by maxxie114** [2B2TMCBE/MobPlugin#4]
Add new auto spawn task for phantom, dolphins, fishes, and drowned.

**Comment by the-tuxedo-cat** [comment]
For random spawns in? So addition to mob plugin or something?

**Comment by maxxie114** [comment]
Yes random spawn in already exist in this plugin, I just want u to add spawn support for the four new mobs

**Comment by PetteriM1** [comment]
Good luck with that, this time just copy pasting others code wont help

**Comment by maxxie114** [comment]
I never copy paste other's code ok?

**Comment by maxxie114** [comment]
I never copy paste other's code ok?

**Comment by PetteriM1** [comment]
Spawning for water animals is added to latest mob plugin version

**Comment by maxxie114** [comment]
ok thx
